name: flutter_simple_shopify
description: A new Flutter package which provides help in creating a mobile app of a shopify store.
version: 0.0.25-alpha
homepage: https://github.com/ThinkSimple/flutter_simple_shopify
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  graphql_flutter:
      git:
          url: https://github.com/filip-zalewski-netbulls/graphql-flutter.git
          path: packages/graphql_flutter
          ref: be2ff7620ba294bdaaa05ff880784bd84b93d08b
  hive: ^2.1.0
  json_serializable: 6.8.0
  intl: 0.19.0
  json_annotation: 4.9.0

dev_dependencies:
  build_runner: 2.4.6
  freezed: 2.4.5
