name: flutter_simple_shopify
description: A new Flutter package which provides help in creating a mobile app of a shopify store.
version: 0.0.25-alpha
homepage: https://github.com/ThinkSimple/flutter_simple_shopify
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  graphql_flutter: 5.1.2
  hive: ^2.1.0
  json_serializable: 6.7.1
  intl: 0.18.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: 2.4.6
  freezed: 2.4.5
